add aws cli

diff --git a/scripts/install_dependencies b/scripts/install_dependencies
--- a/scripts/install_dependencies
+++ b/scripts/install_dependencies
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Exit on error
+set -o errexit -o pipefail
+
 # Update yum
 yum update -y
 
@@ -31,7 +34,7 @@ sed -i 's#DocumentRoot "/var/www/html"#DocumentRoot "/var/www/html/public"#' /et
 sed -e 's/DirectoryIndex.*/DirectoryIndex index.html index.php/' -i /etc/httpd/conf/httpd.conf
 
 # Get Composer, and install to /usr/local/bin
-if [ ! -f "/usr/local/bin/composer" ];then
+if [ ! -f "/usr/local/bin/composer" ]; then
     php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
     php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
     php composer-setup.php --install-dir=/usr/bin --filename=composer
@@ -45,3 +48,16 @@ service httpd restart
 
 # Setup apache to start on boot
 chkconfig httpd on
+
+# Ensure aws-cli is installed and configured
+if [ ! -f "/usr/bin/aws" ]; then
+    curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+    unzip awscli-bundle.zip
+    ./awscli-bundle/install -b /usr/bin/aws
+fi
+
+# Ensure AWS Variables are available
+if [[ -z "$AWS_ACCOUNT_ID" || -z "$AWS_DEFAULT_REGION " ]]; then
+    echo "AWS Variables Not Set.  Either AWS_ACCOUNT_ID or AWS_DEFAULT_REGION"
+    exit 1
+fi
